#!/bin/bash

tmux new-session -d -s btm-session 'btm' # start new detached tmux session, run htop
tmux split-window                        # split the detached tmux session
tmux send 'btm' ENTER                    # send 2nd command 'htop -t' to 2nd pane. I believe there's a `--target` option to target specific pane.
tmux a                                   # open (attach) tmux session.

# TODO attach to session
tmux new-windows -d -n pacman

# homebrew
tmux split-window
tmux split-window
# brew update
# sudo pacman -Suyy
tmux split-window -h
yay -Suyy
tmux split-window
