#!/usr/bin/env sh

quit() {
  rm /tmp/jiantie-list.lock
  rm /tmp/fzf-nova.lock
  pkill -x kitty
}

export FZF_DEFAULT_OPTS="\
--reverse \
--border rounded \
--no-info \
--pointer='' \
--marker=' ' \
--ansi \
--color='16,bg+:-1,gutter:-1,prompt:5,pointer:5,marker:6,border:4,label:4'"

selected=$(
  jiantie list --format "id,type,data,tags" | fzf --delimiter " " --with-nth='2..' --preview "jiantie decode {} -m" \
    --preview-window=up,65%
)

[[ -z $selected ]] && quit

jiantie decode "$selected" --format "data" | wl-copy &
wait $!
quit
