#!/usr/bin/env sh

export FZF_DEFAULT_OPTS="\
--reverse \
--border rounded \
--no-info \
--pointer='' \
--marker=' ' \
--ansi \
--color='16,bg+:-1,gutter:-1,prompt:5,pointer:5,marker:6,border:4,label:4'"

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

selectd=$(fd . --full-path $CURRENT_DIR --type f | grep '_' | sort | fzf -e -i --delimiter _ --with-nth='2..')

quit() {
  rm /tmp/fzf-nova.lock
  pkill -x kitty
}

[[ -z $selectd ]] && quit

sh $selectd
