#!/usr/bin/env bash

# If the operating system is not Arch Linux, exit the script successfully
if [ ! -f /etc/arch-release ]; then
  exit 0
fi

# Calculate updates for each service
AUR=$(yay -Qua | wc -l)
OFFICIAL=$(pacman -Qu | wc -l)
COUNT=$((OFFICIAL + AUR))

show() {
  if [[ "$COUNT" = "0" ]]; then
    echo ""
  else
    echo " $COUNT"
  fi
  exit 0
}

# Case/switch for each service updates
case $1 in
update)
  # touch "/tmp/alacritty.lock"
  footclient --title update-sys -e sh -c 'cd; tmux new -A -s update-sys "sudo pacman -Syu"' &
  wait $!
  killall -SIGUSR2 waybar
  ;;
aur)
  COUNT=$AUR
  show
  ;;
official)
  COUNT=$OFFICIAL
  show
  ;;
*)
  show
  ;;
esac
