#!/usr/bin/env sh

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $CURRENT_DIR/utils.sh

hide
sleep .3

hyprpicker --format hex | head -c -1 | wl-copy
[ -z $(wl-paste) ] && quit
convert -size 100x100 xc:$(wl-paste) /tmp/color.png
dunstify --icon=/tmp/color.png "$(wl-paste)" "Copied to your clipboard!"

quit
