os:
  editCommand: "" # see 'Configuring File Editing' section
  editCommandTemplate: "{{editor}} {{filename}}"
  openCommand: ""
gui:
  showIcons: true
customCommands:
  - key: z
    command: ~/.config/bin/gc
    context: files
    loadingText: Commitizen prompt
    subprocess: true

git:
  paging:
    colorArg: always
    useConfig: false
    # pager: detal --dark paging=never
